### PR TITLE
Nawglan/update meta yml

### PR DESCRIPTION
**Pull request by nawglan**
cpan-prc.  update the META.yml file to have correct author and added a provides section.  kwalitee related changes.

### CODE REVIEW

**Comment by karenetheridge** [comment]
This file is generated by Makefile.PL, so that file should be updated instead.

**Comment by hanfried** [comment]
Thanks a lot for the PR. I merged it and it is released in version 0.35 https://github.com/hanfried/test-warn/commit/9c78de0ddc9114cf466d38e0707255537cba173e (currently uploading to PAUSE).

**Comment by karenetheridge** [comment]
None of these changes actually made it into the shipped distribution, because META.* are generated at 'make dist' time and all the changes made here were overwritten. Makefile.PL needs to be updated instead!

**Comment by hanfried** [comment]
D'oh, I tried to make it better in https://github.com/hanfried/test-warn/commit/53397153ccc571111fbc12f07e323912f327bfef and uploaded it as version 0.36 to PAUSE.

**Pull request merged**
